### ISSUE TITLE
Compiler Stack Depth Error with Foundry Nightly/Stable, Works on v0.3.0

### ISSUE THREAD

**Issue by snissn** [FilOzone/fws-payments#88]
I'm encountering a compilation error when using the **nightly** or **`stable`** version of Foundry via `foundryup --tag stable` or `--tag nightly`, while everything works fine with **v0.3.0**, which is also what the GitHub build bot uses.

#### ✅ Works:

```bash
foundryup --tag v0.3.0
forge build  # ✅ successful
```

#### ❌ Fails on stable/nightly:

```bash
foundryup --tag stable
forge build
```

Error:

```
[⠔] Solc 0.8.25 finished in 1.40s
Error: Compiler run failed:
Error: Yul exception:Cannot swap Slot RET[cleanup_uint256] with Variable expr_48931_component_5_mpos: too deep in the stack by 4 slots in [ var_rateQueue_slot RET[cleanup_uint256] var_rail_48809_slot var_skipArbitration var_targetEpoch RET var_railId var_segmentEndBoundary RET[cleanup_uint256] 0x08 var_currentRate var_totalOperatorCommission var_totalPaymentFee var_rail_48809_slot var_totalSettledAmount RET[read_from_storage_split_offset_uint256] var_processedEpoch expr_48931_component expr_48931_component_1 expr_48931_component_2 expr_48931_component_3 expr_48931_component_5_mpos ]
memoryguard was present.
make: *** [build] Error 1
```

---

### 💭 Thoughts

It seems like something in the latest Foundry tooling or the Yul optimizer path introduced a breaking change — possibly increased sensitivity to stack depth or a regression in the IR pipeline.

While it's acceptable to pin to `v0.3.0`, this may create issues for developers or downstream projects expecting compatibility with the latest `foundryup` versions.

---

### ✅ Potential Fixes

1. **Update the Makefile** to explicitly install `v0.3.0` via `foundryup --tag v0.3.0`
2. **Document the Foundry version requirement** (v0.3.0) in `README.md` or build instructions
3. **Investigate & resolve stack-depth issue** in newer Foundry builds / IR passes

**Comment by Chaitu-Tatipamula** [comment]
@snissn i can work on this, can you assign it to me?

**Comment by snissn** [comment]
Hey @Chaitu-Tatipamula I appreciate you jumping in on this! I’m not really a stakeholder here to make the call either way, so I’ll defer to whoever’s closest to the implementation or longer-term plan. Glad it’s in good hands though!
